<?php


namespace Yepwoo\LaravelParser\Test;

use PHPUnit\Framework\TestCase as MainTestCase;
use Illuminate\Http\Request;
use ReflectionClass;

class TestCase extends MainTestCase
{
    /**
     * @var
     */
    protected $request;

    /**
     * @var
     */
    protected $model;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->request = new Request();
        $this->request->merge(['with' => 'relationStub']);
    }

    /**
     * @throws \ReflectionException
     */
    protected static function getMethod($name, $class) {
        $class = new ReflectionClass($class);
        $method = $class->getMethod($name);
        $method->setAccessible(true);
        return $method;
    }
}
